language: node_js

services:
  - docker

node_js:
  - "10.15.3"

addons:
  chrome: stable

# matrix:
#   include:
#   - name: "Functional Tests"
#     env: TEST_SUITE=start-func

script: make start-func
