language: node_js

node_js:
  - 14

addons:
  chrome: stable

install:
  - "yarn && yarn build"

after_failure:
  - make upload_screenshots

jobs:
  include:
    - stage: UT
      script: yarn test
    - stage: FT
      script: yarn ft
    - stage: deploy
      script: make deploy
      if: branch = master AND type = push
