language: node_js

services:
  - docker

node_js:
  - "10.15.3"

addons:
  chrome: stable

after_failure:
  - make upload_screenshots

jobs:
  include:
    - stage: test
      script: make start-func
    - stage: deploy
      before_script:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        - sudo apt-get update
        - sudo apt-get install libstdc++-4.9-dev
      script: make deploy
      if: branch = master AND type = push