sudo: required
services:
  - docker
language: ruby
cache:
  bundler: true
  yarn: true
addons:
  chrome: stable
rvm:
  - 2.5.1
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install
script: make test
after_failure:
  - bundle exec rake upload_screenshots