language: node_js

services:
  - docker

addons:
  chrome: stable

before_install:
  - rvm install 2.6.1
  - bundle install
  - nvm install v10.15.3

matrix:
  include:
  - name: "Unit Test"
    env: TEST_SUITE=start-unit
  - name: "Functional Tests"
    env: TEST_SUITE=start-func
  - name: "Integration Tests"
    env: TEST_SUITE=start-int

before_script:
  - echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  - echo fs.inotify.max_queued_events=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

script: make $TEST_SUITE

after_failure:
  - bundle exec rake upload_screenshots
