sudo: required
services:
  - docker
language: ruby
cache:
  bundler: true
  yarn: true
addons:
  chrome: stable
rvm:
  - 2.6.1
install:
  - bundle install
  - nvm install v10.15.3
  - node -v
  - npm i -g yarn
  - yarn install
jobs:
  include:
    - stage: unit tests
      script: make start-unit
    - stage: functional tests
      script: make functional-up
    - stage: integration tests
      script: make integration-up

after_failure: 
  - bundle exec rake upload_screenshots