language: node_js

services:
  - docker

node_js:
  - "10.15.3"

addons:
  chrome: stable

after_failure:
  - make upload_screenshots

jobs:
  include:
    - stage: test
      script: make start-func
    - stage: deploy
      script: make deploy
      if: branch = master AND type = push