language: node_js

services:
  - docker

node_js:
  - "10.15.3"

addons:
  chrome: stable

after_failure:
  - make upload_screenshots

jobs:
  include:
    - stage: test
      script: echo "TEST"
    - stage: deploy
      script: make deploy
      if: branch = master AND type = push

# Needed by nodegit to install properly on linux box
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libssl-dev
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - lcov