version: '2'
services:
  webpack:
    build:
      context: ../..
      dockerfile: Docker/Dockerfiles/webpack
    volumes_from:
      - interface
    links:
      - interface
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: bash -c "/usr/src/app/bin/webpack-dev-server"
    ports:
      - 3035:3035
    tty: true
    env_file: ../../development.env
  interface:
    extends:
      file: app.yml
      service: interface
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
    env_file: ../../development.env
