version: '2'
services:
  interface:
    extends:
      file: app.yml
      service: interface
    environment:
     - RAILS_ENV=development
    ports:
      - 3002:3002
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
