version: '2'
services:
  interface:
    extends:
      file: app.yml
      service: interface
    environment:
     - RAILS_ENV=test
     - APP_DOMAIN=interface
     - PORT=3002
     - SELENIUM_DOMAIN=selenium
     - MOCKSERVER_DOMAIN=mockserver
    ports:
     - 3002:3002
    volumes:
      - /box
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails assets:precompile && bundle exec rails s -p 3002 -b '0.0.0.0'"
  tester:
    build:
      context: ../..
      dockerfile: Docker/Dockerfiles/tester
    volumes_from:
      - interface
    links:
      - selenium
      - interface
      - mockserver
    depends_on:
      - interface
    environment:
      - INTERACTIVE
      - RAILS_ENV=test
      - APP_DOMAIN=interface
      - PORT=3002
      - SELENIUM_DOMAIN=selenium
      - MOCKSERVER_DOMAIN=mockserver
    tty: true
  mockserver:
    image: jamesdbloom/mockserver:mockserver-5.3.0
    ports:
      - 1080:1080
    tty: false
    logging:
      driver: "none"
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
    - 4444:4444
    - 5900
    links:
      - interface
    tty: false
    logging:
      driver: "none"
