version: '2'
services:
  interface:
    extends:
      file: app.yml
      service: interface
    environment:
     - RAILS_ENV=test
     - DOCKER_HOST=interface
    ports:
     - 3002:3002
    volumes:
      - /myapp
      - /box
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails assets:precompile && bundle exec rails s -p 3002 -b '0.0.0.0'"
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
    - 4444:4444
    - 5900
    links:
      - interface
    tty: false
  tester:
    build:
      context: ../..
      dockerfile: Docker/Dockerfiles/tester
    volumes_from:
      - interface
    links:
      - selenium
      - interface
      - mockserver
    depends_on:
      - interface
    environment:
      - MLAB_URI
      - API_DOMAIN
  mockserver:
    image: jamesdbloom/mockserver:mockserver-5.3.0
    ports:
      - 1080:1080
    environment:
      - LOG_LEVEL=INFO
