version: '2'
services:
  interface:
    extends:
      file: app.yml
      service: interface
    environment:
     - RAILS_ENV=test
    ports:
     - 3002:3002
    volumes:
      - /myapp
      - /box
    command: Docker/scripts/start.sh
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
    - 4444:4444
    - 5900
    links:
      - interface
    tty: false
  tester:
    build:
      context: ../..
      dockerfile: Docker/Dockerfiles/tester
    volumes_from:
      - interface
    volumes:
      - ../../spec/frontend/test_results:/myapp/spec/frontend/test_results
    links:
      - selenium
      - interface
    depends_on:
      - interface
    environment:
      - MLAB_URI
      - MLAB_USER
      - MLAB_PASSWORD
      - MLAB_BASE_URL
