version: '3'
services:
  web:
    build:
      context: ../../
      dockerfile: Docker/Dockerfiles/Dockerfile
    environment:
     - RAILS_ENV=test
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../../:/myapp
    ports:
      - 3002:3002

  selenium-hub:
    image: selenium/hub
    ports:
    - 4444:4444

  chrome:
    image: selenium/node-chrome
    links:
    - selenium-hub:hub
    ports:
      - 5900
