version: '2'
services:
  interface:
    extends:
      file: app.yml
      service: interface
    environment:
     - RAILS_ENV=test
    ports:
     - 3002:3002
    volumes_from:
      - bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
    - 4444:4444
    - 5900
    links:
      - interface
  tester:
    build:
      context: ../..
      dockerfile: Docker/Dockerfiles/tester
    volumes_from:
      - bundle
      - interface
    links:
      - selenium
      - interface
    depends_on:
      - interface
  bundle:
    image: mmsinterface_interface
    volumes:
      - /box