version: '2'
services:
  interface:
    extends:
      file: app.yml
      service: interface
    environment:
      - RAILS_ENV=test
      - MLAB_URI
      - SLACK_ADMIN_TOKEN
      - GMAIL_PASSWORD
      - GMAIL_USERNAME
      - BT_ENV
      - BT_PRIVATE_KEY
      - BT_PUBLIC_KEY
      - BT_MERCHANT_ID
      - SIGNATURES_FOLDER
      - SECRET_KEY_BASE
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rspec --format progress --format html --out /myapp/spec/rspec_results.html"