version: '2'
services:
  interface:
    extends:
      file: app.yml
      service: interface
    environment:
      - RAILS_ENV=test
    volumes_from:
      - bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rspec --format progress --format html --out /myapp/spec/rspec_results.html"
  bundle:
    image: mmsinterface_interface
    volumes:
      - /box